easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation

#*entities:
       # Category:
          #  class: App\Entity\Category
        #Livre:
          #  class: App\Entity\Livre
       # User:
          #  class: App\Entity\User
